# soundtrackdiscs mods.toml
modLoader="javafml"
loaderVersion="[44,)"
license="MIT"
issueTrackerURL="https://github.com/thenamesnano/Soundtrack-Discs/issues"

[[mods]]
modId="soundtrackdiscs"
version="${file.jarVersion}"
displayName="Soundtrack Discs"
updateJSONURL="https://gist.githubusercontent.com/thenamesnano/8a3091c530036e43f12923840a55605c/raw"
displayURL="https://www.curseforge.com/minecraft/mc-mods/soundtrack-discs"
logoFile="icon.png"
credits="Thanks to boingobongo69 for the idea on Minecraft Forum, and Darklzar for helping fix issue #1!."
authors="Nano (thenamesnano)"
description='''
A mod that adds in music discs from the Minecraft OST.
'''

[[dependencies.soundtrackdiscs]]
    modId="forge"
    mandatory=true
    versionRange="[44.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soundtrackdiscs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
