# This is an soundtrackdiscs mods.toml file.
modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="soundtrackdiscs"
version="1.16.5-1.0.0"
displayName="Soundtrack Discs"
displayURL="https://www.curseforge.com/minecraft/mc-mods/soundtrack-discs"
logoFile="icon.png"
credits="Thanks to boingobongo69 for the idea on Minecraft Forum, and Darklzar for helping fix issue #1!."
authors="Nano (thenamesnano)"
description='''
A mod that adds in music discs from the Minecraft OST.
'''

[[dependencies.soundtrackdiscs]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soundtrackdiscs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
